// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cuahangdidong.Data;

namespace cuahangdidong.Migrations
{
    [DbContext(typeof(cuahangdidongContext))]
    [Migration("20220315003946_Rating")]
    partial class Rating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cuahangdidong.Models.didong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChứVụ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GíaBán")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgàyPhátHành")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThểLoại")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("didong");
                });
#pragma warning restore 612, 618
        }
    }
}
